sudo: required

language: minimal

services: docker

before_install:
  - docker -v

install:
  - docker build -t digirati/madoc-search .

cache:
  bundler: true
  directories:
    - $HOME/docker

deploy:
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-search
    on:
      tags: true

  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-search
    on:
      branch: master

  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-search
    on:
      branch: feature/ual

if: |
  branch = master OR \
  branch = feature/ual OR \
  type = pull_request OR \
  tag IS present
